<table>
  <tr>
    <th>Error</th>
    <th>Cause</th>
    <th>Trial Solution</th>
  </tr>
  <tr>
    <td>TypeError: \'tuple\' object is not callable</td>
    <td>A set/list/dictionary of tuples have a missing comma. python considers the second tuple ase an argument to a function defined by first tuple.</td>
    <td>use a comma to separate tuples.</td>
  </tr>
</table>
